### PR TITLE
add patch-add-resourceRequirements for SchedulingStrategy

### PR DESCRIPTION
**Pull request by ddh-open**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y 
fix https://github.com/KusionStack/konfig/issues/118

#### 2. What is the scope of this PR (e.g. component or file name):

utils/str2resource_requirements.k

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [ ] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [x] Other

#### 6. Release note

Please refer to [Release Notes Language Style Guide](https://kusionstack.io/docs/governance/release-policy/) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by ddh-open** [comment]
---
我已阅读 CLA 文件并特此注明 CLA
---

**Comment by ddh-open** [comment]
- - -
   I have read the CLA Document and I hereby sign the CLA
   - - -

**Comment by doudaohu** [comment]
- - -
   I have read the CLA Document and I hereby sign the CLA
   - - -

**Comment by SparkYuan** [comment]
recheck

**Comment by SparkYuan** [comment]
recheck

**Review by SparkYuan — APPROVED** [review]
lgtm

**Pull request merged**
