### PR TITLE
add patch-add-resourceRequirements for Server

### LINKED ISSUE #118: resource 模板不能单独配置 limit和request
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### PR DESCRIPTION
**Pull request by ddh-open**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y 

fix #118

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [ ] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [x] Other

#### 6. Release note

Please refer to [Release Notes Language Style Guide](https://kusionstack.io/docs/governance/release-policy/) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by SparkYuan** [comment]
@ddh-open  Thank you for your contribution👏🏻. Please sign the CLA above and complete the questions in the PR template.

**Comment by ddh-open** [comment]
我已阅读 CLA 文件并特此签署 CLA

**Comment by ddh-open** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ddh-open** [comment]
- - -
   I have read the CLA Document and I hereby sign the CLA
   - - -

**Comment by ddh-open** [comment]
> **CLA Assistant Lite 机器人：** 感谢您的提交，我们非常感谢。与许多开源项目一样，我们要求您签署我们的[贡献者许可协议](https://github.com/KusionStack/.github/blob/main/CLA.md)，然后我们才能接受您的贡献。您只需发布与以下格式相同的 Pull 请求评论即可签署 CLA。
> 
> 我已阅读 CLA 文件并特此签署 CLA
> 
> 您可以通过在此 Pull 请求中评论**重新检查来重新触发此机器人**

   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -

**Pull request closed without merging**
