### PR TITLE
Feat add openkruise models to konfig/base

### PR DESCRIPTION
**Pull request by LeoLiuYan**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

 - [ ] N
 - [✅] Y 

#12 

#### 2. What is the scope of this PR (e.g. component or file name):

konfig

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [ ✅] N
- [ ] Y

### CODE REVIEW

**Comment by LeoLiuYan** [comment]
> github-actions

I have read the CLA Document and I hereby sign the CLA

**Comment by LeoLiuYan** [comment]
recheck

**Comment by LeoLiuYan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by Peefy — APPROVED** [review]
LGTM

**Review by howieyuen — APPROVED** [review]
/lgtm

**Pull request merged**
